/**
 * Hometax CSV Export
 * ─────────────────────────────────────────────────────────────────────────────
 * Generates CSV files matching the Hometax (홈택스) upload format for:
 *   - VAT declaration (부가세 신고서)
 *   - Expense ledger (경비 명세서)
 *
 * Every file starts with a disclaimer comment line so reviewers are warned.
 */

import Papa from 'papaparse'
import type { VATCalculation, ReportPeriod } from '@/lib/tax/calculator'
import type { ClassifiedTransaction } from '@/lib/ai/optimizer'
import type { Transaction } from '@/types/transaction'

// ─── Constants ────────────────────────────────────────────────────────────────

const CSV_DISCLAIMER =
  '# 본 파일은 AI 생성 참고용입니다. 실제 신고 전 반드시 검토하세요.\n' +
  '# This file was generated by TaxFlow AI. Please review before filing.\n'

const INCOME_CODE_LABELS: Record<string, string> = {
  '101': '과세매출',
  '102': '면세수입',
  '103': '영세율매출',
}

const EXPENSE_CODE_LABELS: Record<string, string> = {
  '201': '매입공제',     '202': '카드매입',      '203': '현금영수증매입',
  '301': '인건비',       '302': '임차료',         '303': '차량유지비',
  '304': '접대비',       '305': '광고선전비',     '306': '통신비',
  '307': '소모품비',     '308': '장비구입비',     '309': '소프트웨어구독',
  '310': '콘텐츠제작비', '311': '외주편집비',
  '401': '불공제매입',   '402': '개인지출',
}

function categoryLabel(code: string | null): string {
  if (!code) return '미분류'
  return INCOME_CODE_LABELS[code] ?? EXPENSE_CODE_LABELS[code] ?? code
}

function vatBasis(amount: number): number {
  // Supply value = amount ÷ 1.1 (reverse-calculate from VAT-inclusive amount)
  return Math.round(Math.abs(amount) / 1.1)
}

function vatAmount(amount: number): number {
  return Math.round(Math.abs(amount) - vatBasis(amount))
}

function evidenceType(tx: ClassifiedTransaction): string {
  const cat = tx.taxCategory ?? ''
  if (cat === '202') return '신용카드'
  if (cat === '203') return '현금영수증'
  if (cat === '201') return '세금계산서'
  if (tx.receiptRequired && !tx.manuallyReviewed) return '영수증미첨부'
  return '기타'
}

function transactionType(cat: string | null): string {
  if (!cat) return '미분류'
  if (['101','102','103'].includes(cat)) return '매출'
  if (['201','202','203'].includes(cat)) return '매입(공제)'
  if (['301','302','303','304','305','306','307','308','309','310','311'].includes(cat)) return '필요경비'
  if (cat === '401') return '매입(불공제)'
  return '기타'
}

// ─── Public exports ───────────────────────────────────────────────────────────

/**
 * Generate VAT Declaration CSV matching the 홈택스 부가세 신고서 업로드 양식.
 *
 * Columns: 일련번호, 거래일자, 공급가액, 세액, 거래구분, 과세유형
 * Summary rows appended at the bottom for the declaration totals.
 */
export function generateVATDeclarationCSV(
  vatData: VATCalculation,
  period: ReportPeriod
): string {
  const summaryRows = [
    {
      일련번호: '',
      거래일자: '',
      공급가액: '',
      세액: '',
      거래구분: '',
      과세유형: '',
      비고: '──── 부가세 신고 요약 ────',
    },
    {
      일련번호: '',
      거래일자: `${period.year}-${period.quarter ?? '연간'}`,
      공급가액: vatData.taxableSales,
      세액: vatData.outputVAT,
      거래구분: '과세매출',
      과세유형: vatData.isSimplified ? '간이과세' : '일반과세',
      비고: `VAT율 ${(vatData.vatRate * 100).toFixed(0)}%`,
    },
    {
      일련번호: '',
      거래일자: '',
      공급가액: vatData.taxFreeIncome,
      세액: 0,
      거래구분: '면세수입',
      과세유형: '면세',
      비고: '',
    },
    {
      일련번호: '',
      거래일자: '',
      공급가액: '',
      세액: vatData.deductibleInputVAT,
      거래구분: '매입세액공제',
      과세유형: '',
      비고: '공제 가능 매입세액',
    },
    {
      일련번호: '',
      거래일자: '',
      공급가액: '',
      세액: vatData.vatPayable,
      거래구분: '납부세액',
      과세유형: '',
      비고: '최종 납부 세액',
    },
  ]

  const csv = Papa.unparse(summaryRows, { header: true })
  return CSV_DISCLAIMER + csv
}

/**
 * Generate expense ledger CSV for attaching to a tax return.
 *
 * Columns: 일련번호, 날짜, 거래내역, 금액, 공급가액, 세액, 분류, 세금코드, 증빙유형, 비고
 */
export function generateExpenseCSV(transactions: ClassifiedTransaction[]): string {
  // Sort: income first, then expenses; within each group, by date ascending
  const sorted = [...transactions].sort((a, b) => {
    const aIncome = (a.taxCategory ?? '').startsWith('1')
    const bIncome = (b.taxCategory ?? '').startsWith('1')
    if (aIncome !== bIncome) return aIncome ? -1 : 1
    return a.transactionDate.localeCompare(b.transactionDate)
  })

  const rows = sorted.map((tx, idx) => ({
    일련번호: idx + 1,
    날짜: tx.transactionDate,
    거래내역: tx.description,
    금액: tx.amount,
    공급가액: vatBasis(tx.amount),
    세액: vatAmount(tx.amount),
    분류: categoryLabel(tx.taxCategory),
    세금코드: tx.taxCategory ?? '',
    거래구분: transactionType(tx.taxCategory),
    증빙유형: evidenceType(tx),
    영수증필요: tx.receiptRequired ? 'Y' : 'N',
    검토완료: tx.manuallyReviewed ? 'Y' : 'N',
    비고: tx.riskFlag && tx.riskFlag.length > 0 ? tx.riskFlag.join(', ') : '',
  }))

  const csv = Papa.unparse(rows, { header: true })
  return CSV_DISCLAIMER + csv
}

// ─── Backward-compat export (used by legacy code) ────────────────────────────

export function generateHometaxCsv(transactions: Transaction[]): string {
  const rows = transactions.map((tx) => ({
    거래일자: tx.date,
    적요: tx.description,
    금액: tx.amount,
    구분: tx.category,
  }))
  return CSV_DISCLAIMER + Papa.unparse(rows, { header: true })
}
